const fs=require('fs');const d=require('docx');
const {Document,Packer,Paragraph,TextRun,HeadingLevel,Table,TableRow,TableCell,WidthType,ShadingType,BorderStyle,AlignmentType,ImageRun}=d;
const INK="1f2a37",BLUE="2E5A88";
function P(r){return new Paragraph({spacing:{after:120,line:276},children:Array.isArray(r)?r:[new TextRun({text:r,size:21})]});}
function lead(b,r){return P([new TextRun({text:b,bold:true,size:21}),new TextRun({text:r,size:21})]);}
function H1(t){return new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:240,after:120},children:[new TextRun({text:t,bold:true,color:BLUE,size:26})]});}
function cap(t){return new Paragraph({spacing:{before:60,after:180},children:[new TextRun({text:t,italics:true,size:18,color:"5b6b7b"})]});}
const TW=9026;
function cell(t,{w,head=false,bold=false,align="left"}={}){return new TableCell({width:{size:w,type:WidthType.DXA},shading:head?{type:ShadingType.CLEAR,fill:BLUE,color:"auto"}:{type:ShadingType.CLEAR,fill:"auto",color:"auto"},margins:{top:40,bottom:40,left:80,right:80},children:[new Paragraph({alignment:align==="left"?AlignmentType.LEFT:AlignmentType.CENTER,children:[new TextRun({text:t,bold:head||bold,color:head?"FFFFFF":INK,size:17})]})]});}
function table(h,rows,w){const hr=new TableRow({tableHeader:true,children:h.map((x,i)=>cell(x,{w:w[i],head:true,align:i===0?"left":"center"}))});const tr=rows.map(r=>new TableRow({children:r.map((c,i)=>cell(String(c),{w:w[i],align:i===0?"left":"center",bold:i===0}))}));return new Table({width:{size:TW,type:WidthType.DXA},columnWidths:w,rows:[hr,...tr]});}
function fig(p,w,h){return new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:120,after:60},children:[new ImageRun({type:"png",data:fs.readFileSync(p),transformation:{width:w,height:h}})]});}
const k=[];
k.push(new Paragraph({spacing:{after:40},border:{bottom:{style:BorderStyle.SINGLE,size:12,color:BLUE}},children:[new TextRun({text:"Annexure E — PRISM in Action on CAS ActSim Data",bold:true,size:30})]}));
k.push(new Paragraph({spacing:{after:60},children:[new TextRun({text:"A detailed, claim-level demonstration and validation of PRISM under an independent data-generating process: how it behaves, what is new, and the conditions under which it works best.",italics:true,size:20,color:"5b6b7b"})]}));
k.push(new Paragraph({spacing:{after:200},children:[new TextRun({text:"Companion to PRISM (Draft 3). Prepared by Dr. Rohan Yashraj Gupta (FIA, FIAI). 28 September 2026. All data synthetic. Internal-driven form (no external stream). Accompanying file: PRISM_ActSim_Workbook.xlsx.",size:18,color:"5b6b7b"})]}));

// Executive summary box
k.push(new Paragraph({shading:{type:ShadingType.CLEAR,fill:"eef3f8",color:"auto"},border:{left:{style:BorderStyle.SINGLE,size:24,color:BLUE}},spacing:{after:160},children:[new TextRun({text:"In brief. ",bold:true,size:21}),new TextRun({text:"On loss data generated claim-by-claim with CAS ActSim, PRISM detects the gradual and subtle severity inflections that plain BOCPD misses entirely, ignores one-off outlier quarters that make plain BOCPD false-alarm every time, and matches it on abrupt jumps. Its effectiveness scales with the steepness of the change. The internal predictor-stability signal is, if anything, stronger on realistic claim-level data than on the native process, because claim-level noise leaves a tighter baseline residual. All data are synthetic.",size:21})]}));

k.push(H1("E.1 Purpose and setup"));
k.push(P("Section 4 established PRISM's behaviour on panels drawn from the detector's own observation model. This annexure shows PRISM operating end-to-end on an independent generator: the loss side of every panel is simulated one claim at a time with CAS ActSim (Zhang; validated by the CAS Risk Working Group) and aggregated into a quarterly trend exhibit, exactly as an actuary builds one from a claims listing. The accompanying workbook, PRISM_ActSim_Workbook.xlsx, contains one such panel in full — every individual claim (Sheet 1), the quarterly aggregation with live formulas rebuilding it from the claims (Sheet 2), and the trend exhibit with the detector overlays (Sheet 3). Because ActSim generates claims, not economic indicators, the external stream is not exercised here; the method demonstrated is PRISM driven by its internal signals, with the outlier-robust adjustment of E.3."));

k.push(H1("E.2 Data and calibration"));
k.push(P("Each panel is 40 quarters with the inflection onset at quarter 24 and a 16-quarter frozen baseline. The book carries a few thousand claims per quarter across three lognormal severity classes. Before drawing any conclusion, the in-control series is confirmed against target moments (Table E1)."));
k.push(table(["In-control metric","Target","ActSim","Verdict"],[["Mean severity log-return","0.00850","0.00844","within tolerance"],["SD severity log-return","0.01600","0.01495","within tolerance"],["KS test vs Normal, p-value","p > 0.05","0.317","cannot reject"],["Lag-1 autocorrelation of log-return","≈ 0 (native −0.02)","−0.464","structural — see E.5"]],[3200,1900,1900,2026]));
k.push(cap("Table E1. Calibration of the ActSim panel (60 in-control replications). Mean and dispersion match target. Claim-level generation induces a strong negative return autocorrelation absent from the native process — a genuine feature of real-style sampling noise, discussed in E.5."));

k.push(H1("E.3 The method demonstrated — PRISM(adjusted)"));
k.push(P("PRISM raises a Bayesian changepoint hazard using internal predictor-stability signals: a frozen baseline model is fitted on the first 16 quarters, and its out-of-sample residual on the monitored log-severity feeds the hazard, so a modest but persistent run of evidence is treated as a regime change sooner than the loss data alone would justify. Under claim-level data a single anomalous quarter is the key adversarial case, so a reversion-aware (Hampel/median) filter is placed ahead of the detector: it replaces an isolated spike with the local median but leaves a sustained shift untouched. This is PRISM(adjusted). Detection is reported as on-time — a first alarm within the window from two quarters before onset to six quarters after — with a late alarm not counted as a detection."));

k.push(H1("E.4 PRISM in action — a worked panel"));
k.push(P("Figure E1 follows one gradual panel (the panel in the workbook). Mean severity creeps upward with no single dramatic quarter. The loss-only monitor's alarm probability wanders near 0.1–0.2 and never approaches the 0.5 threshold — it does not call the turn in 40 quarters. PRISM(adjusted), with its hazard lifted as the frozen baseline begins to misfit, crosses the threshold and declares the inflection. The mechanism in miniature: not a cleverer reading of the loss data, but permission, granted by the internal signal, to treat an accumulating drift as a regime change."));
k.push(fig("results/fig_example.png",560,404));
k.push(cap("Figure E1. One gradual ActSim panel. Top: mean severity creeps up through the 8-quarter ramp from onset. Bottom: plain BOCPD (red) peaks at 0.18 and never crosses 0.5; PRISM(adjusted) (blue) crosses at quarter 33. The workbook's Trend_Exhibit sheet shows the same panel with the severity pulling above its fitted baseline."));

k.push(H1("E.5 New finding — why the loss-only benchmark is blind to a slow turn"));
k.push(P("A central question is why plain BOCPD, which catches abrupt jumps almost perfectly, is nearly blind to a gradual inflection. Running severity-only BOCPD on 100 gradual and 100 abrupt panels under each generator makes the mechanism explicit (Figure E2, Table E2). BOCPD is not failing: it detects abrupt shocks 91% (native) and 99% (ActSim). But a gradual inflection lifts the average quarterly log-return by only about +0.010, while the quarter-to-quarter noise has standard deviation ~0.015 — the signal is smaller than the noise, no single quarter is surprising, and the changepoint probability never builds to the 0.5 threshold (its peak averages 0.25–0.35). This is the reserve-strengthening problem restated: the loss data alone cannot see a slow turn."));
k.push(P("A second, subtler effect is specific to claim-level data. ActSim returns carry a negative lag-1 autocorrelation (−0.33 to −0.46), because sampling noise makes the quarterly mean mean-revert — a high quarter tends to be followed by a low one. Consecutive returns partly cancel, so a sustained drift is even harder to distinguish, and the loss-only monitor is blinder still on ActSim (1%) than on the native process (7%). The same effect slightly helps on an abrupt shock, where a one-off jump stands out more against a mean-reverting background."));
k.push(fig("results/fig_bocpd_diag.png",560,283));
k.push(cap("Figure E2. Left: on a gradual panel the loss-only alarm probability never reaches 0.5 on either generator. Right: BOCPD catches abrupt shocks (both) but is blind to gradual inflections (both), with peak alarm probability far below threshold. This blindness is precisely the gap PRISM's covariate hazard is built to fill."));
k.push(table(["Severity-only BOCPD","Native (PRISM data)","ActSim data"],[["Abrupt — detection","0.91","0.99"],["Gradual — detection","0.07","0.01"],["Gradual — peak alarm prob (mean)","0.35","0.25"],["Return lag-1 autocorrelation","+0.02","−0.33"]],[3626,2700,2700]));
k.push(cap("Table E2. The loss-only monitor is near-blind to gradual inflections on both generators; ActSim is blinder still because its returns mean-revert. Abrupt shocks are caught on both."));

k.push(H1("E.6 Primary results — loss-only BOCPD vs PRISM(adjusted)"));
k.push(P("Across 80 paired replications per regime, the two-regime pattern reproduces under the independent generator (Table E3, Figure E3). On an abrupt shock both monitors detect essentially every panel. On a gradual inflection the loss-only monitor is entirely blind (0 of 80) while PRISM(adjusted) detects a fifth of panels on time; the paired McNemar test is decisive. A weaker subtle inflection is caught less often but the direction is unchanged."));
k.push(table(["Regime (on-time detection)","BOCPD","PRISM(adjusted)","95% CI","McNemar"],[["Abrupt shock","1.000","0.988","[.933,.998]","tie (0 vs 1)"],["Gradual inflection","0.000","0.200","[.127,.300]","16 vs 0, p=3.1×10⁻⁵"],["Subtle inflection","0.000","0.075","[.035,.154]","6 vs 0, p=3.1×10⁻²"]],[3000,1400,1900,1500,1226]));
k.push(cap("Table E3. On-time detection under ActSim (80 paired replications per regime; no external stream)."));
k.push(fig("results/fig_h2h_v3.png",560,230));
k.push(cap("Figure E3. On-time detection on real inflections (left) and false-alarm rate on flat data and one-off outlier quarters (right). Plain BOCPD false-alarms on every outlier; PRISM(adjusted) holds outliers near its flat-data rate while detecting the gradual and subtle changes BOCPD misses."));
k.push(lead("Outlier robustness. ","A transient one-quarter spike makes plain BOCPD false-alarm 100% of the time; the reversion filter cuts PRISM(adjusted)'s false-alarm rate on that spike to about 13%, close to its 9% flat-data rate. The filter removes the isolated spike but leaves a sustained shift intact — so PRISM ignores a freak quarter yet still reacts to a real regime change."));

k.push(H1("E.7 Detectability across the curvature of a gradual inflection"));
k.push(P("Holding the pre-inflection drift fixed and varying how steeply the growth climbs after onset traces a family of gradual inflections of increasing curvature. The loss-only monitor detects none at any steepness; PRISM(adjusted)'s on-time detection scales monotonically and its median lag shrinks as the bend sharpens (Table E4, Figure E4)."));
k.push(table(["Curvature","Post-shift growth","BOCPD on-time","PRISM(adjusted) on-time","Median lag (q)"],[["Gentle","5.1%/yr","0.000","0.025","12"],["Mild","6.8%/yr","0.000","0.062","9"],["Steep","8.5%/yr","0.000","0.162","7"],["Very steep","10.2%/yr","0.000","0.400","7"]],[1900,2100,1900,2100,1026]));
k.push(cap("Table E4. On-time detection and median detection lag across gradual inflections of increasing curvature (80 replications each). BOCPD detects none at any curvature."));
k.push(fig("results/fig_curve_v3.png",560,233));
k.push(cap("Figure E4. On-time detection rises with steepness (left) and median lag shrinks (right). A gentle drift near the baseline is caught rarely and late; once the bend is moderately sharp, detection climbs and the lag settles near seven quarters."));

k.push(H1("E.8 What is new in this annexure"));
k.push(P("Relative to Section 4, the ActSim study adds five findings:"));
k.push(P([new TextRun({text:"1. The advantage survives an independent generator. ",bold:true,size:21}),new TextRun({text:"PRISM's edge over the loss-only benchmark on gradual inflections holds — and strengthens — when the data are simulated claim-by-claim rather than drawn from the detector's own model.",size:21})]));
k.push(P([new TextRun({text:"2. The internal signal is stronger on realistic data. ",bold:true,size:21}),new TextRun({text:"Because claim-level sampling noise leaves a tighter baseline residual than random-walk noise, the internal predictor-stability stream does more of the work on ActSim than on the native process.",size:21})]));
k.push(P([new TextRun({text:"3. The benchmark's blindness is quantified and explained. ",bold:true,size:21}),new TextRun({text:"A gradual change lifts the mean return below the noise floor, so BOCPD's alarm probability never reaches threshold — with a mechanism (E.5) rather than an assertion.",size:21})]));
k.push(P([new TextRun({text:"4. Claim-level noise is mean-reverting. ",bold:true,size:21}),new TextRun({text:"ActSim returns carry a strong negative autocorrelation absent from the native process, a structural feature of aggregating claims to a quarterly mean, which mildly misspecifies the Gaussian UPM and makes the loss-only monitor blinder still.",size:21})]));
k.push(P([new TextRun({text:"5. The outlier weakness is fixed. ",bold:true,size:21}),new TextRun({text:"A reversion-aware filter turns the one-off-outlier false-alarm rate from 100% (plain BOCPD) to about 13%, without cost to genuine detection.",size:21})]));

k.push(H1("E.9 How PRISM works best"));
k.push(P("The results locate where the method earns its keep, and where it does not:"));
k.push(P([new TextRun({text:"• On gradual and subtle inflections, not abrupt jumps. ",bold:true,size:21}),new TextRun({text:"Abrupt shocks are caught by the loss-only monitor already; PRISM adds nothing there. Its value is concentrated on the slow, creeping turns — the social-inflation case that drives quiet adverse development.",size:21})]));
k.push(P([new TextRun({text:"• The sharper the bend, the sooner and more reliably. ",bold:true,size:21}),new TextRun({text:"Detection rises from a few percent at a gentle 5%/yr bend to 40% on time at a steep 10%/yr bend, with the lag falling from twelve to seven quarters.",size:21})]));
k.push(P([new TextRun({text:"• On a well-populated book. ",bold:true,size:21}),new TextRun({text:"More claims per quarter lower the sampling-noise floor, so the internal baseline residual is cleaner and a small drift becomes visible sooner.",size:21})]));
k.push(P([new TextRun({text:"• With the reversion filter engaged. ",bold:true,size:21}),new TextRun({text:"On real-style data with occasional freak quarters, the filter is what keeps PRISM from over-reacting; without it, sensitivity comes at an outlier-driven false-alarm cost.",size:21})]));
k.push(P([new TextRun({text:"• As confirmation, read as such. ",bold:true,size:21}),new TextRun({text:"Under internal signals alone PRISM confirms a developing turn several quarters after onset — earlier than matured loss data would force recognition, but not instantaneous. Strict pre-onset warning is the role of the external stream, deferred to the roadmap.",size:21})]));

k.push(H1("E.10 Limitations and roadmap"));
k.push(P("The data are synthetic; ActSim provides claim-level realism and independence from the detector, not real experience. The external stream — the paper's primary early-warning mechanism — is not exercised here, so this annexure speaks to the internal-driven form. The dominant remaining limitation is detection lag. The roadmap, in priority order: (i) real or synthetic external leading indicators, the only stream that carries information before the losses move; (ii) a CUSUM statistic in place of the rolling-mean internal signal, to react to small persistent drifts sooner; (iii) claim-level distributional monitoring of the tail and spread that aggregation to a single mean discards; and (iv) validation on real experience."));

k.push(H1("E.11 Reproducibility"));
k.push(P([new TextRun({text:"Reproducible from fixed seeds. Modules: ",size:21}),new TextRun({text:"prism_robust.py",font:"Consolas",size:19}),new TextRun({text:" (PRISM(adjusted), head-to-head, outliers), ",size:21}),new TextRun({text:"prism_curve.py",font:"Consolas",size:19}),new TextRun({text:" (curvature), ",size:21}),new TextRun({text:"diag_bocpd.py",font:"Consolas",size:19}),new TextRun({text:" (benchmark blindness), ",size:21}),new TextRun({text:"gen_workbook_panel.py",font:"Consolas",size:19}),new TextRun({text:" (the worked panel and workbook). Loss data from CAS ActSim; detector core prism_sim.py imported unchanged. All data synthetic.",size:21})]));

const doc=new Document({styles:{default:{document:{run:{font:"Calibri",size:21,color:INK}}}},sections:[{properties:{page:{margin:{top:1440,bottom:1440,left:1440,right:1440}}},children:k}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("PRISM_Draft3_AnnexureE.docx",b);console.log("written",b.length);});
